5 create todo list markup
chrislicodes/vanilla-todo-list pull request #7
Opened 2021-01-25 18:14 UTC by chrislicodes

## What

Created todo list markup

## Deliveries

index.html
sprites.svg

Closes #5

2021-01-26 12:12 UTC, artdaw requested changes
## Overall comments

1. Remove all classes attributes since we don't apply any style yet.
2. Remove all <div> elements since they are not needed for this task, they have no semantic. They might be used in future once we style our list of todos.
3. Please, address all single comments

2021-01-26 12:12 UTC, artdaw commented on index.html
> +    <link rel="stylesheet" href="./css/style.css">
You don't have styles so far, so please remove it/

2021-01-26 12:12 UTC, artdaw commented on index.html
> +    <script defer src="./js/app.js"></script>
You also don't have JS, so please remove it.

2021-01-26 12:12 UTC, artdaw commented on index.html
> +                            placeholder="The next thing I have to do is .." required>
```suggestion
                            placeholder="The next thing I have to do is .." required="required">
```

or

```suggestion
                            placeholder="The next thing I have to do is .." required="true">
```

2021-01-26 12:12 UTC, artdaw commented on index.html
> +                            <input type="date" name="date" max="2099-12-31" class="input-date" required>
```suggestion
                            <input type="date" name="date" max="2099-12-31" class="input-date" required="required">
```

or 

```suggestion
                            <input type="date" name="date" max="2099-12-31" class="input-date" required="true">
```

2021-01-26 12:12 UTC, artdaw commented on index.html
> +                            <input type="time" name="time" value="13:30" class="input-time" required>
```suggestion
                            <input type="time" name="time" value="13:30" class="input-time" required="required">
```

or

```suggestion
                            <input type="time" name="time" value="13:30" class="input-time" required="true">
```

2021-01-26 12:12 UTC, artdaw commented on index.html
> +                            <button class="input-btn btn">Add Task :&#41;</button>
It is better to set `type` for button explicitly. It is `type="submit"` by default.

2021-01-26 12:12 UTC, artdaw commented on index.html
> +            </div>
If this is a list of 2 tasks it is not semantically right. 
You MUST use `<ul>` or `<ol>` to define lists in HTML.

2021-01-26 12:12 UTC, artdaw commented on index.html
> +        </div>
I don't remember we have a filtering functionality, so I guess this MUST be removed.

2021-01-26 12:12 UTC, artdaw commented on index.html
> +</html>
Please, add empty line at the end of the file.

2021-01-26 12:12 UTC, artdaw commented on index.html
> +        </h1>
1. This is not semantically right. You have a choice of different headers from `h1` to `h6`, so h1 might be a primary header and h2 might be used as secondary header/
2. No need for spans.

2021-02-01 08:08 UTC, artdaw commented on index.html
> +                </button>
## Suggestion

I would think about using [`<article>`](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/article) element to group description, date and actions into 1 widget.

2021-02-01 20:02 UTC, chrislicodes commented on index.html
> +                </button>
I added the article tag as discussed, also each article element requires an Heading Tag, so I replaced the p tag.

2021-02-02 10:30 UTC, artdaw approved these changes

2021-02-02 11:51 UTC, merged